# Generated by Django 5.1.2 on 2024-10-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.RemoveField(
            model_name='university',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='university',
            name='website',
        ),
    ]
