# Generated by Django 5.1.2 on 2024-10-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='event_attachments/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_events', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='profiles.profile'),
        ),
    ]
