# Generated by Django 5.1.2 on 2024-10-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_university_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='code',
            field=models.CharField(default='default_code', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Include the university details in this description.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Event location.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Enter the event title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the category.'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(help_text='Enter the event category name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.university'),
        ),
    ]
