# Generated by Django 5.1.2 on 2024-10-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_option_is_correct_poll_expiration_time_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='poll',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='poll_banners/'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='poll',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='poll',
            name='show_share_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll'),
        ),
    ]
