# Generated by Django 5.1.2 on 2024-10-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_background_color_poll_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_expiration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
