# Generated by Django 5.1.2 on 2024-10-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_allow_expiration_poll_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='multi_option',
            field=models.BooleanField(default=False),
        ),
    ]
