# Generated by Django 5.1.2 on 2024-10-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_voted_at_vote_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
