# Generated by Django 5.1.2 on 2024-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_vote_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
