# Generated by Django 5.1.2 on 2024-10-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_vote_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_language',
        ),
        migrations.AlterField(
            model_name='poll',
            name='allow_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
