# Generated by Django 5.1.2 on 2024-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_poll_poll_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('question', 'Question'), ('opinion', 'Opinion Poll')], default='opinion', max_length=10),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
